// <auto-generated />
namespace TampaInnovation.DataAccess.Migrations.History
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemovingExtraField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovingExtraField));
        
        string IMigrationMetadata.Id
        {
            get { return "201606042224208_RemovingExtraField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
