CREATE TABLE [dbo].[BedUnitInventory]
(
	[BedUnitInventoryId] INT NOT NULL PRIMARY KEY,
	[IsActive] BIT NULL,
	[Availability] NVARCHAR(50), 
	[Name] NVARCHAR(50), 
	[BedType] NVARCHAR(50), 
	[HouseholdType] NVARCHAR(50) NULL,
	[Provider] NVARCHAR(50) NULL,
	[ProviderId] INT NULL,
	[McKinneyVento] BIT NULL,
	[TargetPopulationARetired] NVARCHAR(50) NULL,
	[TargetPopulationBRetired] NVARCHAR(50) NULL,
	[InventoryStartDate] DATETIME NULL,
	[InventoryEndDate] DATETIME NULL,
	[HMISEndDate] DATETIME NULL,
	[HMISStartDate] DATETIME NULL,
	[BedInventory] INT NULL,
	[CHBedInventory] INT NULL,
	[HMISBeds] INT NULL,
	[UnitInventory] INT NULL,
	[VeteranBedInventory] INT NULL,
	[YouthBedsInventory] INT NULL,
	[YouthBedsInventoryOnlyAges18To24] INT NULL,
	[YouthBedsInventoryOnlyUnderAge18] INT NULL,
	[YouthBedsInventoryOnlyYouthUnderAge24] INT NULL,
	[ProviderCreating] NVARCHAR(50) NULL,
	[DateAdded] DATETIME NULL,
	[ProviderUpdating] NVARCHAR(50) NULL,
	[DateUpdated] DATETIME NULL
)
