namespace TampaInnovation.Models
{
    public class Provider
    {
        public string Active { get; set; }
        public string ProviderUsesActivitypoint { get; set; }
        public string AffiliatedWithAResidentialProject { get; set; }
        public string AirsCompliant { get; set; }
        public string AirsDesignationId { get; set; }
        public string Aka { get; set; }
        public string Brochures { get; set; }
        public string ProviderUsesCallpoint { get; set; }
        public string CapacityType { get; set; }
        public string CescProvider { get; set; }
        public string CocCode { get; set; }
        public string ContinuumProjectProvider { get; set; }
        public string OfficialUpdateRequests { get; set; }
        public string DateAdded { get; set; }
        public string OfficialUpdateDate { get; set; }
        public string DateUpdated { get; set; }
        public string Description { get; set; }
        public string ChangeDescription { get; set; }
        public string DirectServiceCode { get; set; }
        public string Eligibility { get; set; }
        public string FederalEmployerIdNumber { get; set; }
        public string ProviderUsesClientpoint { get; set; }
        public string FacilityType { get; set; }
        public string Geocode { get; set; }
        public string HandicapAccess { get; set; }
        public string Hours { get; set; }
        public string HudHmisProvider { get; set; }
        public string GranteeId { get; set; }
        public string HousingType { get; set; }
        public string OrganizationIdentifier { get; set; }
        public string SiteType { get; set; }
        public string MethodForTrackingEmergencyShelterUtilization { get; set; }
        public string IntakeProcedure { get; set; }
        public string IsShelter { get; set; }
        public string Languages { get; set; }
        public string LastUpdateRequestDate { get; set; }
        public string ProviderMaintaining { get; set; }
        public string ProviderUsesMeasurementTools { get; set; }
        public string Name { get; set; }
        public string Operational { get; set; }
        public string OrganizationMakingChange { get; set; }
        public string OrganizationRequestingChange { get; set; }
        public string ParentProvider { get; set; }
        public string PrimaryAddressId { get; set; }
        public string PrimaryContactId { get; set; }
        public string PrimaryTelephoneId { get; set; }
        public string PrincipalSite { get; set; }
        public string PrintedDirectory { get; set; }
        public string ProgramFees { get; set; }
        public string ProgramTypeCode { get; set; }
        public string ProviderBillsForMedicaid { get; set; }
        public string ProviderCreating { get; set; }
        public string ProviderGrantType { get; set; }
        public string ProviderId { get; set; }
        public string ProviderLevel { get; set; }
        public string LegalStatus { get; set; }
        public string ProviderUpdating { get; set; }
        public string ServeAllGeographies { get; set; }
        public string ServiceCapacity { get; set; }
        public string ServiceTransactionWorkflow { get; set; }
        public string ProviderUsesShelterpoint { get; set; }
        public string ShelterRequirements { get; set; }
        public string ShelterServiceCode { get; set; }
        public string ShowOnPublicSite { get; set; }
        public string ProgramSiteConfigurationType { get; set; }
        public string ProviderUsesSkanpoint { get; set; }
        public string UsesServicepoint { get; set; }
        public string SupportiveServicesForVeteranFamiliesProvider { get; set; }
        public string TargetPopulation { get; set; }
        public string UserCreating { get; set; }
        public string UserUpdating { get; set; }
        public string VolunteerOpportunities { get; set; }
        public string WebsiteAddress { get; set; }
        public string PersonMakingChange { get; set; }
        public string PersonRequestingChange { get; set; }
        public string Wishlist { get; set; }
        public string YearOfIncorporation { get; set; }
    }
}